<?php

	// These shouldn't need altering

	$BIN_DIR_PATH = "../bin/";
	$TEXTURE_DIR_PATH = "textures/";
	$IMAGE_DIR_PATH = "images/";
	$GABORMAGIMG_DIR_PATH = "gabormagimgs/";

	$MIN_TEXTURE_SIZE = 50*50;
	$MIN_GABORMAGIMG_SIZE = 50*50;

	// [HISTOGRAM_COMPARISON_TYPE] COULD BE INTERSECT, EMDL1, DD
	$HISTOGRAM_COMPARISON_TYPE = "EMDL1";

	$GABOR_MAG_ORIENTATION_LIMIT = 4;
	$GABOR_MAG_SCALE_LIMIT = 4;

?>
